-- MySQL Script generated by MySQL Workbench
-- Sun Jun 23 01:27:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projectdb` ;

-- -----------------------------------------------------
-- Table `projectdb`.`airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`airplanes` (
  `plane_id` INT(11) NOT NULL AUTO_INCREMENT,
  `capacity` INT(11) NULL DEFAULT NULL,
  `make` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `planeNumber` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`plane_id`),
  UNIQUE INDEX `UK_nvfov9kokghikkolha4r8tv5c` (`planeNumber` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`airport` (
  `id` BIGINT(20) NOT NULL,
  `airportCode` VARCHAR(255) NULL DEFAULT NULL,
  `airportName` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`crewmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`crewmember` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `crewid` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `position` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`passenger` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `passengerId` INT(11) NULL DEFAULT NULL,
  `passengerLastName` VARCHAR(255) NULL DEFAULT NULL,
  `passengerName` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `sex` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`persistent_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`persistent_logins` (
  `username` VARCHAR(64) NOT NULL,
  `series` VARCHAR(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `last_used` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`series`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectdb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`reservation` (
  `reservationId` BIGINT(20) NOT NULL,
  `bookingDate` DATE NULL DEFAULT NULL,
  `passengerId` INT(11) NOT NULL,
  `referenceNumber` VARCHAR(255) NULL DEFAULT NULL,
  `schueduleId` INT(11) NOT NULL,
  PRIMARY KEY (`reservationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`role` (
  `role_id` INT(11) NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`schuedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`schuedule` (
  `id` BIGINT(20) NOT NULL,
  `arriavaleAirport` VARCHAR(255) NOT NULL,
  `arrivaleaDate` DATE NOT NULL,
  `departureAirport` VARCHAR(255) NULL DEFAULT NULL,
  `departureDate` DATE NULL DEFAULT NULL,
  `planeId` INT(11) NULL DEFAULT NULL,
  `planeNumber` INT(11) NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`user` (
  `id` INT(11) NOT NULL,
  `active` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectdb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectdb`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `projectdb`.`user` (`id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `projectdb`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
